#!/usr/bin/env node
/**
 * scripts/build-index.js
 *
 * 把 src/index-page.js 的内容转译为浏览器可执行格式，inline 注入 index.html
 * 的 `<!-- INLINE:INDEX_PAGE_JS_START -->` ... `<!-- INLINE:INDEX_PAGE_JS_END -->`
 * 标记块中。
 *
 * 设计动机（修复"src/ 暴露在 GitHub Pages 部署路径"问题）：
 *   - 原实现：index.html 用 `<script type="module" src="./src/index-page.js">`
 *     引用 src/ 下的模块 → 若 GitHub Pages 部署仓根，src/ 目录会被原样发布，
 *     不仅泄露实现细节，还违反"首页 = 单一自包含 HTML"的心智模型。
 *   - 修法：保留 src/index-page.js 作为"测试导入的纯函数源"（被 test/unit/index-page.test.js import），
 *     同时通过本脚本自动把它的内容 inline 进 index.html，部署路径上不再出现 src/。
 *   - 浏览器 `<script>`（非 module）不支持 `export` 语法 → 转译规则：
 *       1) `export function NAME(...)`  → `function NAME(...)`  并收集 NAME
 *       2) `export { a, b, c }`         → 整行移除
 *       3) 文件末尾追加 `window.IndexPage = { NAME1, NAME2, ... }` 供页面逻辑引用
 *
 * 用法：
 *   node scripts/build-index.js           # 写回 index.html
 *   node scripts/build-index.js --check   # CI / npm test 用的 drift 检测（只读）
 *
 * 安全网：
 *   - 标记必须存在于 index.html，否则 build 失败（防止"无声地把 inline 块丢空"）
 *   - --check 模式下，若 inline 内容与 src 不一致立即 exit 1
 *   - 整个文件 CRLF → LF 归一后再比对，规避 Windows git checkout 字节漂移
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const SRC = path.join(ROOT, 'src/index-page.js');
const INDEX = path.join(ROOT, 'index.html');

const MARKER_START = '<!-- INLINE:INDEX_PAGE_JS_START -->';
const MARKER_END = '<!-- INLINE:INDEX_PAGE_JS_END -->';

/**
 * 把 src/index-page.js 的 ES module 源码转译为浏览器可执行（非 module）源码。
 * 返回转译后字符串 + 收集到的 export 名字列表。
 *
 * @param {string} srcContent
 * @returns {{ code: string, names: string[] }}
 */
export function transform(srcContent) {
  const names = [];
  // CRLF → LF 归一，规避 Windows checkout 引入的字节差异
  let out = srcContent.replace(/\r\n/g, '\n');
  // 1) export function NAME(...) → function NAME(...)
  out = out.replace(/^export\s+function\s+([A-Za-z0-9_$]+)/gm, (m, name) => {
    names.push(name);
    return `function ${name}`;
  });
  // 2) 移除 `export { a, b, c }` / `export {a,b}` 这类行
  out = out.replace(/^export\s*\{[^}]*\}\s*;?\s*\n?/gm, '');
  // 3) 在末尾追加 window.IndexPage 全局对象
  if (names.length > 0) {
    out += `\n// === auto-generated by build-index.js ===\nwindow.IndexPage = { ${names.join(', ')} };\n`;
  }
  return { code: out, names };
}

/**
 * 把 inlined code 包装到 <script> 块中，替换 index.html 的 INLINE 标记。
 *
 * 注意：build / check 共用一份"内联 code"（= transform 输出）作 single source of truth，
 * 任何"额外注释"必须放在 <script> 标签**外部**的 HTML 注释里 —— 否则 check 提取的
 * <script> 内容会和 transform 输出产生 drift。
 */
function buildBlock(code) {
  return [
    MARKER_START,
    '<!-- 以下内容由 scripts/build-index.js 从 src/index-page.js 自动生成。',
    '     改 src/index-page.js 后跑 npm run build:index 重新生成。 -->',
    '<script>',
    code,
    '</script>',
    MARKER_END,
  ].join('\n');
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function findInlineBlock(html) {
  const re = new RegExp(`${escapeRegex(MARKER_START)}([\\s\\S]*?)${escapeRegex(MARKER_END)}`);
  return html.match(re);
}

/**
 * 主流程：读源 + 转译 + 替换 + 写回。
 * 返回 { changed: boolean, expected: string } —— 后者供 --check 比对。
 */
export function build() {
  if (!existsSync(SRC)) {
    throw new Error(`源文件不存在: ${SRC}`);
  }
  if (!existsSync(INDEX)) {
    throw new Error(`index.html 不存在: ${INDEX}`);
  }
  const html = readFileSync(INDEX, 'utf-8');
  if (!findInlineBlock(html)) {
    throw new Error(`index.html 缺少 inline 标记: ${MARKER_START} ... ${MARKER_END}`);
  }
  const srcContent = readFileSync(SRC, 'utf-8');
  const { code } = transform(srcContent);
  const newBlock = buildBlock(code);
  const re = new RegExp(`${escapeRegex(MARKER_START)}[\\s\\S]*?${escapeRegex(MARKER_END)}`);
  const newHtml = html.replace(re, newBlock);
  if (newHtml === html) {
    return { changed: false, expected: code };
  }
  writeFileSync(INDEX, newHtml, 'utf-8');
  return { changed: true, expected: code };
}

/**
 * 检测模式：若 index.html 的 inline 块与 src 转译后不一致，立即 exit 1。
 * 用于 CI drift 检测 + npm test 入口。
 */
export function check() {
  if (!existsSync(SRC)) throw new Error(`源文件不存在: ${SRC}`);
  if (!existsSync(INDEX)) throw new Error(`index.html 不存在: ${INDEX}`);
  const html = readFileSync(INDEX, 'utf-8');
  const m = findInlineBlock(html);
  if (!m) {
    throw new Error(`index.html 缺少 inline 标记`);
  }
  const sm = m[1].match(/<script>([\s\S]*?)<\/script>/);
  if (!sm) {
    throw new Error(`inline 块缺少 <script> 标签`);
  }
  const actual = sm[1].replace(/\r\n/g, '\n').trim();
  const { code: expected } = transform(readFileSync(SRC, 'utf-8'));
  const expTrim = expected.replace(/\r\n/g, '\n').trim();
  if (actual !== expTrim) {
    throw new Error(
      `index.html inline 内容与 src/index-page.js 不一致\n` +
        `  期望长度: ${expTrim.length} chars\n` +
        `  实际长度: ${actual.length} chars\n` +
        `  修复: 运行 \`npm run build:index\` 重新生成 inline 块`,
    );
  }
}

function main() {
  const mode = process.argv[2];
  try {
    if (mode === '--check') {
      check();
      console.log('[ok] index.html inline 内容与 src/index-page.js 一致');
    } else {
      const { changed } = build();
      if (changed) {
        console.log('[ok] 已更新 index.html（inline from src/index-page.js）');
      } else {
        console.log('[ok] index.html inline 已是最新，无需写入');
      }
    }
  } catch (err) {
    console.error(`[FAIL] ${err.message}`);
    process.exitCode = 1;
  }
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  main();
}
